name: Release Plugin

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (without v prefix)'
        required: true
        default: ''

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: '.'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl, zip
          tools: composer:v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install PHP dependencies
        working-directory: .
        run: composer install --no-dev --optimize-autoloader

      - name: Install JS dependencies
        working-directory: .
        run: npm ci

      - name: Build assets
        working-directory: .
        run: npm run build

      - name: Create plugin zip
        working-directory: .
        run: npm run plugin-zip

      - name: Get version
        id: get_version
        working-directory: .
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Armada Delivery For WooCommerce v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            ./armada-plugin.zip
          body: |
            ## Armada Delivery For WooCommerce v${{ steps.get_version.outputs.VERSION }}
            
            A WooCommerce extension that integrates with Armada Delivery service, allowing merchants to easily ship orders, track deliveries, and manage shipping information.
            
            ### Installation
            
            1. Download the plugin zip file
            2. Go to WordPress Admin > Plugins > Add New > Upload Plugin
            3. Upload the zip file and activate the plugin
            4. Configure the plugin settings under WooCommerce > Settings > Armada Delivery
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
